add some graphics
opentelekomcloud-docs/docsportal pull request #142
Opened 2023-12-07 21:00 UTC by Nils-Magnus

2024-01-05 13:41 UTC, tischrei commented
recheck

2024-01-05 13:58 UTC, tischrei requested changes

2024-01-05 13:58 UTC, tischrei commented on doc/source/additional/sd-manual.rst
> +  .. figure:: /_static/images/sd/1-operational.png
all images are not rendered

2024-01-30 15:07 UTC, Nils-Magnus commented
recheck

2024-02-13 13:02 UTC, tischrei commented
@Nils-Magnus we will not have the content here. Please transfer the content to: https://gitea.eco.tsi-dev.otc-service.com/docs/status-dashboard

2024-02-13 13:02 UTC, closed without merging