add first blueprint
opentelekomcloud-docs/docsportal pull request #17
Opened 2022-02-08 18:14 UTC by gtema

2022-02-09 12:55 UTC, vladimirhasko commented on doc/source/blueprint_cce_vault.rst
> +TLS secrets are kept in the Vault. They are being read by Vault Agent component
too long sentence, I'm getting lost in it. Can you split it two sentences and make it more understandable (especially the middle part)

2022-02-09 12:55 UTC, vladimirhasko commented on doc/source/blueprint_cce_vault.rst
> +storage). For that a policy that gives a read only access to the /tls/zk* and
For that a policy that gives probably should be reformulated for example:
Therefore policy which gives...

2022-02-09 12:55 UTC, vladimirhasko commented on doc/source/blueprint_cce_vault.rst
> +authorize to Vault the token it gets can be used during next 2 hours. This need
if its ttl is 3 hours they it should be used for next 3 hours, right?

2022-02-09 12:55 UTC, vladimirhasko commented on doc/source/blueprint_cce_vault.rst
> +Deploying Zookeeper
it looks to me like the second half of blueprint is too simple.
Maybe more information about configuration per each step would be appreciated. Not only pasted code.

2022-02-09 12:59 UTC, kucerakk commented on doc/source/blueprint_cce_vault.rst
> +running in the every pod of Zookeeper service, where it writes certificates
...in every pod...

2022-02-09 12:59 UTC, kucerakk commented on doc/source/blueprint_cce_vault.rst
> +onto the file system where Zookeeper expectes them and also updates
...expects...

2022-02-09 12:59 UTC, kucerakk commented on doc/source/blueprint_cce_vault.rst
> +   :caption: CCE and Vault overview
this does not seem very much as Caption on the rendered page...perhaps it would be good to make at least one extra blank line after

2022-02-09 12:59 UTC, kucerakk commented on doc/source/blueprint_cce_vault.rst
> +certificates once they got changed in Vault allowing rotation without service
I am just wondering if it needs a POD restart on a new certificate on a filesystem or zookeeper will automatically re-read it from FS

2022-02-09 12:59 UTC, kucerakk commented on doc/source/blueprint_cce_vault.rst
> +Authority. To allow further multiple different CCE clusters to use vault a
sounds to me a bit strange..."further multiple different CCE clusters"  perhaps (just an idea) "to allow further CCE clusters" would be sufficient

2022-02-09 12:59 UTC, kucerakk commented on doc/source/blueprint_cce_vault.rst
> +from zookeeper namespace to get access to the TLS secrets stored in vault (KV
KV - key value  ... I think might be good to at least write down the KV = key value

2022-02-09 12:59 UTC, kucerakk commented on doc/source/blueprint_cce_vault.rst
> +A time to live of 3 hours is being used here meaning that once application
you used 2 hours in the example above

2022-02-09 12:59 UTC, kucerakk commented on doc/source/blueprint_cce_vault.rst
> +not going to do this and only upload generated certificates into the KV store.
would be good to tell the readers that ``` @zk_server.crt ``` means it expects a file named zk_server.crt on the filesystem from where the vault command is executed

2022-02-09 12:59 UTC, kucerakk commented on doc/source/blueprint_cce_vault.rst
> +       {{- with secret "{{ zookeeper.vault_server_cert_path }}" }}{{ .Data.data.certificate }}
you kept here ansible variable references...i think it would be good to rename it to real path instead

2022-02-09 14:33 UTC, Nils-Magnus requested changes
I am not completely sure if this approach of reviewing is the best way for this type of document (a text blog entry), but I tried anyway. Maybe next time I'll try out direct patches?!

I did review only on text and language, not the styling so far. That needs an extra session. :)

2022-02-09 14:33 UTC, Nils-Magnus commented on doc/source/blueprint_cce_vault.rst
> +A lesson on improving that is left to the reader.
[This is not funny] For production setups this example can be easily extended with extra actions.

2022-02-09 14:33 UTC, Nils-Magnus commented on doc/source/blueprint_cce_vault.rst
> +impossible to change the application itself.  Agent is taking care of reading
The agent

2022-02-09 14:33 UTC, Nils-Magnus commented on doc/source/blueprint_cce_vault.rst
> +   access to the tokenreview API. If a dedicated reviewer JWT is used this step
you lost me on "tokenreview API" and "reviewer JWT". Please include some references or spend a sentence on those.

2022-02-09 14:33 UTC, Nils-Magnus commented on doc/source/blueprint_cce_vault.rst
> +   is not necessary, but it also mean a long-living sensitive data is being
mean = means,
s/a//
s/being//

2022-02-09 14:33 UTC, Nils-Magnus commented on doc/source/blueprint_cce_vault.rst
> +   used and permanently transferred over the network. More details on various
s/permanently/frequently/

2022-02-09 14:33 UTC, Nils-Magnus commented on doc/source/blueprint_cce_vault.rst
> +   ways to use Kubernetes token to authorize to Vault `can be found here
s/token/tokens/

2022-02-09 14:33 UTC, Nils-Magnus commented on doc/source/blueprint_cce_vault.rst
> +   <https://www.vaultproject.io/docs/auth/kubernetes#how-to-work-with-short-lived-kubernetes-tokens>`_.
There are various other ways to `authorize Vault with Kubernetes tokens <https://www.vaultproject.io/docs/auth/kubernetes#how-to-work-with-short-lived-kubernetes-tokens>`_.

2022-02-09 14:33 UTC, Nils-Magnus commented on doc/source/blueprint_cce_vault.rst
> +         echo "srvr" | openssl s_client -CAfile /tls/ca.pem -cert /tls/client/tls.crt -key /tls/client/tls.key -connect 127.0.0.1:${1:-2281} -quiet -ign_eof 2>/dev/null | grep Mode
split long line by `openssl` options

2022-02-09 14:33 UTC, Nils-Magnus commented on doc/source/blueprint_cce_vault.rst
> +4. Create Kubernetes ConfigMap with all required configurations
s/Kubernetes/a Kubernetes/

2022-02-09 14:33 UTC, Nils-Magnus commented on doc/source/blueprint_cce_vault.rst
> +           MAIN="-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=$JMXPORT -Dcom.sun.management.jmxremote.authenticate=$JMXAUTH -Dcom.sun.management.jmxremote.ssl=$JMXSSL -Dzookeepe
Split line

2022-02-09 14:33 UTC, Nils-Magnus commented on doc/source/blueprint_cce_vault.rst
> +7. Create StatefulSet replacing `<VAULT_PUBLIC_ADDR>` with address of available
with the address of the Valut server [or with the addresses of the available Vault servers]

2022-02-09 14:33 UTC, Nils-Magnus commented on doc/source/blueprint_cce_vault.rst
> +
I have the feeling that the code snippets are disbalanced long compared to the text explanations. How did you come up with what is in the scripts? Did you just use some defaults and adapted them? Did you follow a reference manual step by step to fill in all those attributes?

If there's a reason for this being so long, that's fine, but then please explain it.

2022-02-09 14:33 UTC, Nils-Magnus commented on doc/source/blueprint_cce_vault.rst
> +With this a production ready Zookeeper service with enabled TLS has been
production-ready

2022-02-09 14:33 UTC, Nils-Magnus commented on doc/source/blueprint_cce_vault.rst
> +deployed sucessfully to the CCE. Vault agent takes care of authorizing to
The Vault agent

2022-02-09 14:33 UTC, Nils-Magnus commented on doc/source/blueprint_cce_vault.rst
> +HashiCorp Vault using Kubernetes service account with short time to live token
Hashicorp
using a
with a

2022-02-09 14:33 UTC, Nils-Magnus commented on doc/source/blueprint_cce_vault.rst
> +and fetches required secrets to the filesystem. In the whole Kubernetes
fetches the required
file system
whole = entire

2022-02-09 14:33 UTC, Nils-Magnus commented on doc/source/blueprint_cce_vault.rst
> +deployment there are no secrets for the application, neither key to the Vault,
neither the key to Vault,

2022-02-09 14:33 UTC, Nils-Magnus commented on doc/source/blueprint_cce_vault.rst
> +not TLS certificates themselves. Even usage of Kubernetes secrets is not
not = nor
usage = using
Not even using Kubernetes secrets is necessary.

2022-02-09 14:33 UTC, Nils-Magnus commented on doc/source/dot/cce_vault_overview.dot
> +digraph cce_vault {
The fonts of the diagram are strange.

2022-02-11 14:07 UTC, gtema commented
Merged as https://github.com/opentelekomcloud-blueprints/docs/pull/1

2022-02-11 14:07 UTC, closed without merging